version: "3.8"

services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: piscineds
            POSTGRES_USER: trobin
        expose:
          - '5432'

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: trobin@student.42.fr
            PGADMIN_DEFAULT_PASSWORD: mysecretpassword
        depends_on:
            - "db"
        ports:
            - 5050:80
        expose:
          - '5432'